"""fourth migration.

Revision ID: 108fadb65735
Revises: 10d5d5cdbd4f
Create Date: 2022-09-07 11:47:38.085967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108fadb65735'
down_revision = '10d5d5cdbd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
