"""Initial migration.

Revision ID: 14349719a68a
Revises: 
Create Date: 2022-09-07 09:11:57.740163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14349719a68a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('firstname', sa.String(length=25), nullable=False),
    sa.Column('fistname', sa.String(length=25), nullable=False),
    sa.Column('middlename', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('group', sa.String(length=25), nullable=True),
    sa.Column('active', sa.String(length=25), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('activation_token', sa.String(length=200), nullable=True),
    sa.Column('deletion_flag', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('credentials')
    op.drop_table('user')
    # ### end Alembic commands ###
