"""second migration.

Revision ID: 3ee6be37bf5a
Revises: 14349719a68a
Create Date: 2022-09-07 11:27:33.067899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee6be37bf5a'
down_revision = '14349719a68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=25), nullable=False))
    op.drop_column('user', 'fistname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fistname', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
