"""Update table

Revision ID: dada18462edd
Revises: 108fadb65735
Create Date: 2022-09-08 13:00:52.952579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dada18462edd'
down_revision = '108fadb65735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_constraint('user_credentialId_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_sessionId_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'sessionId')
    op.drop_column('user', 'credentialId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credentialId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('sessionId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_sessionId_fkey', 'user', 'sessions', ['sessionId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('user_credentialId_fkey', 'user', 'credentials', ['credentialId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('middlename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.VARCHAR(length=255), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('rank', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('activation_token', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deletion_flag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('credentialId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessionId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credentialId'], ['credentials.id'], name='users_credentialId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], name='users_sessionId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
